version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ivmDemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ivm123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ivmDemo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ivm123456
      SPRING_MAIL_HOST: smtp.office365.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ivmtestdemo@hotmail.com
      SPRING_MAIL_PASSWORD: ivm123456
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      SPRING_SECURITY_USER_NAME: cc
      SPRING_SECURITY_USER_PASSWORD: cc123456
      CUSTOM_EMAIL: ivmtestdemo@hotmail.com
    ports:
      - 8080:8080
    depends_on:
      - db

  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_HOST: localhost
      REACT_APP_API_PORT: 8080
    ports:
      - 3000:3000
    depends_on:
      - springboot_app

volumes:
  postgres_data:
